# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu13p-fhgb2104-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/github/memory_system/memory_system.cache/wt [current_project]
set_property parent.project_path D:/github/memory_system/memory_system.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/github/memory_system/memory_system.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/github/memory_system/memory_system.srcs/sources_1/new/replace_fifo_buffer.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cFifo2.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cMutexMerge2_35b.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cSelector2.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cSplitter2.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/contTap.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/delay/delay1U.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/delay/delay1Unit.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/delay/delay2U.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/receiver.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/relay.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/sender.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/Icache.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cFifo1.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/CacheTop.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/Dcache.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/L2Cache.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/MMU.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cSelector7.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cWaitMerge2_64b.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/delay/delay2Unit.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/memorySystemTop.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/pmtRelay.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cLastFifo1.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cMutexMerge2_1b.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/tag_compare.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cPmtFifo2.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cMutexMerge2_outpmt_35b.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cPmtSelector2.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cMutexMerge6_outpmt_6b.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/Dcache_D_V_buffer.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/Dcache_plru_buffer.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cSelector5.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/dcache_plru_evict.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cSelector5_fire2.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cWaitMerge2_2b.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/dcache_tag_compare.v
  D:/github/memory_system/memory_system.srcs/sources_1/new/control/cMutexMerge3_1b.v
}
read_ip -quiet D:/github/memory_system/memory_system.srcs/sources_1/ip/Icache_SRAM_bank/Icache_SRAM_bank.xci
set_property used_in_implementation false [get_files -all d:/github/memory_system/memory_system.srcs/sources_1/ip/Icache_SRAM_bank/Icache_SRAM_bank_ooc.xdc]

read_ip -quiet D:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_dataSram0/Dcache_bank_dataSram0.xci
set_property used_in_implementation false [get_files -all d:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_dataSram0/Dcache_bank_dataSram0_ooc.xdc]

read_ip -quiet D:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_dataSram1/Dcache_bank_dataSram1.xci
set_property used_in_implementation false [get_files -all d:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_dataSram1/Dcache_bank_dataSram1_ooc.xdc]

read_ip -quiet D:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_tagSRAM/Dcache_bank_tagSRAM.xci
set_property used_in_implementation false [get_files -all d:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_tagSRAM/Dcache_bank_tagSRAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Dcache_D_V_buffer -part xcvu13p-fhgb2104-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Dcache_D_V_buffer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Dcache_D_V_buffer_utilization_synth.rpt -pb Dcache_D_V_buffer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
