######################################################################
#
# File name : Dcache_tb_wave.do
# Created on: Sat Aug 03 11:13:26 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
