# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_tagSRAM/Dcache_bank_tagSRAM.xci
# IP: The module: 'Dcache_bank_tagSRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_tagSRAM/Dcache_bank_tagSRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dcache_bank_tagSRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_tagSRAM/Dcache_bank_tagSRAM.xci
# IP: The module: 'Dcache_bank_tagSRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github/memory_system/memory_system.srcs/sources_1/ip/Dcache_bank_tagSRAM/Dcache_bank_tagSRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dcache_bank_tagSRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
