######################################################################
#
# File name : Dcache_tb_simulate.do
# Created on: Sat Aug 03 11:42:21 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L secureip -lib xil_defaultlib xil_defaultlib.Dcache_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {Dcache_tb_wave.do}

view wave
view structure
view signals

do {Dcache_tb.udo}

run 1000ns
