######################################################################
#
# File name : Dcache_tb_compile.do
# Created on: Sun Aug 11 15:52:57 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\software\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
D:\\software\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

D:\\software\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\software\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\software\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"Dcache_tb_time_synth.v" \
"../../../../../memory_system.srcs/sim_1/new/replace_fifo_buffer_tb.v" \
"../../../../../memory_system.srcs/sim_1/new/Icache_tb.v" \
"../../../../../memory_system.srcs/sim_1/new/Dcache_D_V_buffer_tb.v" \
"../../../../../memory_system.srcs/sim_1/new/Dcache_tb.v" \


quit -force

