######################################################################
#
# File name : Dcache_tb_wave.do
# Created on: Sat Aug 03 14:45:28 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
