# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/github/memory_system/memory_system.srcs/sources_1/ip/Icache_SRAM_bank/Icache_SRAM_bank.xci
# IP: The module: 'Icache_SRAM_bank' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github/memory_system/memory_system.srcs/sources_1/ip/Icache_SRAM_bank/Icache_SRAM_bank_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Icache_SRAM_bank'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/github/memory_system/memory_system.srcs/sources_1/ip/Icache_SRAM_bank/Icache_SRAM_bank.xci
# IP: The module: 'Icache_SRAM_bank' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github/memory_system/memory_system.srcs/sources_1/ip/Icache_SRAM_bank/Icache_SRAM_bank_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Icache_SRAM_bank'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
